In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
from pymongo import MongoClient

import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
# Initialize MongoDB database and collection
client = MongoClient()
db = client['ksdb']
collection = db['full_data']
tab = db['full_data'].find()

In [5]:
import pandas as pd

# read the entire file into a python array
with open('full_data.json', 'rb') as f:
    data = f.readlines()

# remove the trailing "\n" from each line
data = map(lambda x: x.rstrip(), data)

# each element of 'data' is an individual JSON object.
# i want to convert it into an *array* of JSON objects
# which, in and of itself, is one large JSON object
# basically... add square brackets to the beginning
# and end, and have all the individual business JSON objects
# separated by a comma
data_json_str = "[" + ','.join(data) + "]"

# now, load it into pandas
data_df = pd.read_json(data_json_str)

In [176]:
subdf = data_df[:25]
df = subdf.copy()
# df = df.drop('table_id', axis=1)
# df = df.drop('robot_id', axis = 1)
df.head()

,_id,created_at,data,id,robot_id,run_id,table_id
0,{u'$oid': u'582a60d6edad9a1337c6497a'},2016-01-28 12:50:49.416262,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter,Kickstarter_2016-01-28T09_15_08_781Z,Kickstarter
1,{u'$oid': u'582a60d6edad9a1337c6497b'},2016-01-28 12:50:49.416262,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter,Kickstarter_2016-01-28T09_15_08_781Z,Kickstarter
2,{u'$oid': u'582a60d6edad9a1337c6497c'},2016-01-28 12:50:49.416262,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter,Kickstarter_2016-01-28T09_15_08_781Z,Kickstarter
3,{u'$oid': u'582a60d6edad9a1337c6497d'},2016-01-28 12:50:49.416262,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter,Kickstarter_2016-01-28T09_15_08_781Z,Kickstarter
4,{u'$oid': u'582a60d6edad9a1337c64980'},2016-01-28 12:50:49.416262,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter,Kickstarter_2016-01-28T09_15_08_781Z,Kickstarter

In [148]:
def extract_data_features(df):
    df['status'] = df['data'].map(lambda x: x['state'])

    df['project_id'] = df['data'].map(lambda x: x['id'])
    df['creator_id'] = df['data'].map(lambda x: x['creator']['id'])
    df['creator_name'] = df['data'].map(lambda x: x['creator']['name'])

    df['goal'] = df['data'].map(lambda x: x['goal'])
    df['name'] = df['data'].map(lambda x: x['name'])
    df['slug'] = df['data'].map(lambda x: x['slug'])
    df['blurb'] = df['data'].map(lambda x: x['blurb'])

    df['pledged'] = df['data'].map(lambda x: x['pledged'])
    df['cat_name'] = df['data'].map(lambda x: x['category']['name'])
    df['cat_slug'] = df['data'].map(lambda x: x['category']['slug'])
    df['currency'] = df['data'].map(lambda x: x['currency'])

    df['loc_type'] = df['data'].map(lambda x: x['location']['type'])
    df['short_name'] = df['data'].map(lambda x: x['location']['short_name'])
    df['state'] = df['data'].map(lambda x: x['location']['state'])
    df['country'] = df['data'].map(lambda x: x['location']['country'])
    df['spotlight'] = df['data'].map(lambda x: x['spotlight'])
    df['staff_pick'] = df['data'].map(lambda x: x['staff_pick'])
    df['created_at'] = df['data'].map(lambda x: x['created_at'])
    df['launched_at'] = df['data'].map(lambda x: x['launched_at'])
    df['usd_pledged'] = df['data'].map(lambda x: x['usd_pledged'])

    df['backers_count'] = df['data'].map(lambda x: x['backers_count'])
    df['currency_symbol'] = df['data'].map(lambda x: x['currency_symbol'])
    df['static_usd_rate'] = df['data'].map(lambda x: x['static_usd_rate'])
    df['state_changed_at'] = df['data'].map(lambda x: x['state_changed_at'])
    df['disable_communication'] = df['data'].map(lambda x: x['disable_communication'])

    return df

In [149]:
def remove_features(df):
    df = df.drop('table_id', axis=1)
    df = df.drop('robot_id', axis = 1)
    return df

In [177]:
 def get_interval(df):
    df['created_at'] = pd.to_datetime(df.created_at, unit='s')
    df['launched_at'] = pd.to_datetime(df.launched_at,unit='s')
    df['state_changed_at'] = pd.to_datetime(df.state_changed_at,unit='s')

    df['created_at'] = df['created_at'].map(lambda x: x.date())
    df['launched_at'] = df['launched_at'].map(lambda x: x.date())
    df['state_changed_at'] = df['state_changed_at'].map(lambda x: x.date())

    # find interval features
    df['days_to_launch'] = (df['launched_at'] - df['created_at']).map(lambda x:x.days)
    df['proj_live_days'] = (df['state_changed_at'] - df['launched_at']).map(lambda x:x.days)
    return df

In [178]:
df = remove_features(df)
df = extract_data_features(df)
df = get_interval(df)
df.head()

,_id,created_at,data,id,run_id,status,project_id,creator_id,creator_name,goal,...,staff_pick,launched_at,usd_pledged,backers_count,currency_symbol,static_usd_rate,state_changed_at,disable_communication,days_to_launch,proj_live_days
0,{u'$oid': u'582a60d6edad9a1337c6497a'},2014-07-11,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter_2016-01-28T09_15_08_781Z,failed,1038659700,1869250107,Grant Kidd,10,...,False,2014-07-17,6.0,2,$,1.0,2014-07-27,False,6,10
1,{u'$oid': u'582a60d6edad9a1337c6497b'},2014-07-30,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter_2016-01-28T09_15_08_781Z,failed,1238331911,469264203,Caleb Chance,900,...,False,2014-07-30,0.0,0,$,1.0,2014-08-29,False,0,30
2,{u'$oid': u'582a60d6edad9a1337c6497c'},2015-03-17,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter_2016-01-28T09_15_08_781Z,failed,857125548,709510333,Adelfino Corino,2000,...,False,2015-03-19,25.0,1,$,1.0,2015-04-30,False,2,42
3,{u'$oid': u'582a60d6edad9a1337c6497d'},2015-05-08,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter_2016-01-28T09_15_08_781Z,failed,189217262,714853124,James Curtis,900,...,False,2015-05-11,0.0,0,$,1.0,2015-05-31,False,3,20
4,{u'$oid': u'582a60d6edad9a1337c64980'},2015-04-03,"{u'disable_communication': False, u'creator': ...",34165690,Kickstarter_2016-01-28T09_15_08_781Z,failed,1653837117,1828668879,Jonathan Molina,2900,...,False,2015-04-06,40.0,2,$,1.0,2015-05-16,False,3,40

In [179]:
df.loc[20]

_id                                 {u'$oid': u'582a60d6edad9a1337c649a9'}
created_at                                                      2014-07-20
data                     {u'disable_communication': False, u'creator': ...
id                                                                34165685
run_id                                Kickstarter_2016-01-28T09_15_08_781Z
status                                                              failed
project_id                                                       900919506
creator_id                                                      1031356190
creator_name                                                    Kurt Gantz
goal                                                                  9375
name                                                     Zombie Apocalypse
slug                                                     zombie-apocalypse
blurb                    A unique experience to partake in with friends...
pledged                                                                  4
cat_name                                                       Digital Art
cat_slug                                                   art/digital art
currency                                                               USD
loc_type                                                              Town
short_name                                                   Hampstead, MD
state                                                                   MD
country                                                                 US
spotlight                                                            False
staff_pick                                                           False
launched_at                                                     2014-08-06
usd_pledged                                                            4.0
backers_count                                                            2
currency_symbol                                                          $
static_usd_rate                                                        1.0
state_changed_at                                                2014-09-05
disable_communication                                                False
days_to_launch                                                          17
proj_live_days                                                          30
Name: 20, dtype: object

In [169]:
b = dfa.duration_to_launch
b.days

17